### ISSUE TITLE
Spamming /validate and /discord crashes the server

### ISSUE THREAD

**Issue by rinehartj** [MrKwabs/DiscordRewards-Guides#2]
I noticed a heavy lag spikes after the use of any command for this plugin.

**Comment by DominicTurner02** [comment]
This plugin heavily relies on MySQL and this is most likely where the lag is coming from. I wont be changing /validate as you'd only need to use that once and there is no chance of multiple people executing that command. 

As with /Discord there's not much I can do in the current version of the Plugin as it needs to check things such as if the code has been used before, if the user has validated before, if the user already has their rewards etc... 

I have a re-work update planned which should hopefully remove a lot of the lag issues and any complications. This will be done by the BOT individually DMing the User's on Discord, allowing them to log-in to a website which will check their verification status etc... which will remove any need randomly generated codes (which is where a lot of the lag comes from). Expect this sometime in the next two weeks. If you don't feel this is a good idea let me know and I'll think of another solution.

Thanks for letting me know about this issue, I'll update this as and when the new changes happen. For now I suggest adding a cooldown on /Discord & /Code, although I don't expect them to be used so much that it causes lag. 

Let me know if you have any more issues, feel free to open up a new issue here, DM me on Discord or join my [Discord Guild](https://discord.gg/5NA74Fc).
